# Site settings
title: Rotio
email: rotio@rotio.net
url: https://rotio.github.io
description: "Anthony Rotio's personal project site."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 590A00 #80B3FF
  secondary: A81400 #FD6E8A
  secondary-dark: 590A00 #A2122F
  
# Footer settings
footer:
  copyright: Anthony Rotio
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: New York, New York
  
# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
